import React, { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { LayoutDashboard, Package, ShoppingCart, Users, Layers, ClipboardList, FileText, Truck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '../api';
import Modal from './Modal';

const Sidebar = () => {
  const { user } = useAuth();
  const [isReportModalOpen, setIsReportModalOpen] = useState(false);

  const navItems = [
    { path: '/', label: 'Overview', icon: LayoutDashboard, end: true },
    { path: '/orders/new', label: 'New Order (POS)', icon: ShoppingCart },
    { path: '/orders', label: 'Orders', icon: ClipboardList, end: true },
    { path: '/customers', label: 'Customers', icon: Users },
    { path: '/products', label: 'Products', icon: Package, roles: ['Admin', 'DBA'] },
    { path: '/categories', label: 'Categories', icon: Layers, roles: ['Admin', 'DBA'] },
    { path: '/suppliers', label: 'Suppliers', icon: Truck, roles: ['Admin', 'DBA'] },
    { path: '/inventory', label: 'Inventory', icon: Package, roles: ['Admin', 'DBA'] },
  ];

  // Filter items based on role
  const filteredNavItems = navItems.filter(item => {
    if (!item.roles) return true; // Accessible to all (Staff, Admin, DBA)
    return user && item.roles.includes(user.role);
  });

  const handleGenerateReport = async () => {
    setIsReportModalOpen(false);

    try {
      const res = await api.get('/reports/summary');
      const data = res.data;

      const doc = new jsPDF();

      // Title
      doc.setFontSize(20);
      doc.text("Grocery Store Operational Report", 14, 22);

      doc.setFontSize(11);
      doc.text(`Generated By: ${user.role} (${user.user_id})`, 14, 30);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36);

      // Section 1: Summary Metrics
      doc.setFontSize(14);
      doc.text("1. Monthly Overview (Last 30 Days)", 14, 45);

      const summaryData = [
        ['Metric', 'Value'],
        ['Total Orders', data.ordersCount],
        ['Total Revenue', `Rs. ${data.revenue}`],
        ['Avg Order Value', `Rs. ${Number(data.avgOrderValue).toFixed(2)}`]
      ];

      autoTable(doc, {
        startY: 50,
        head: [['Metric', 'Value']],
        body: summaryData.slice(1),
        theme: 'striped',
        headStyles: { fillColor: [66, 66, 66] }
      });

      // Section 2: Top Selling Products
      let finalY = doc.lastAutoTable.finalY + 10;
      doc.text("2. Top 5 Best Selling Products", 14, finalY);

      const topProductsData = data.topProducts.map(p => [p.product_name, p.total_sold]);

      autoTable(doc, {
        startY: finalY + 5,
        head: [['Product Name', 'Units Sold']],
        body: topProductsData,
        theme: 'grid',
        headStyles: { fillColor: [22, 160, 133] }
      });

      // Section 3: Low Selling Products
      finalY = doc.lastAutoTable.finalY + 10;
      doc.text("3. Low Selling Products (Stock Watch)", 14, finalY);

      const lowProductsData = data.lowProducts.map(p => [p.product_name, p.total_sold]);

      autoTable(doc, {
        startY: finalY + 5,
        head: [['Product Name', 'Units Sold']],
        body: lowProductsData,
        theme: 'grid',
        headStyles: { fillColor: [192, 57, 43] }
      });

      doc.save(`Operational_Report_${new Date().toISOString().split('T')[0]}.pdf`);

    } catch (error) {
      console.error(error);
      alert('Failed to generate report');
    }
  };

  const confirmReport = () => setIsReportModalOpen(true);

  return (
    <>
      <aside className="w-64 bg-slate-900 text-slate-300 flex flex-col fixed h-full transition-all duration-300">
        <div className="h-16 flex items-center px-6 border-b border-slate-800">
          <span className="text-xl font-bold text-white tracking-wide">GrocerySys</span>
        </div>

        <nav className="flex-1 py-6 px-3 space-y-1 overflow-y-auto">
          {filteredNavItems.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              end={item.end}
              className={({ isActive }) =>
                `flex items-center px-3 py-2.5 rounded-md transition-colors ${isActive
                  ? 'bg-indigo-600 text-white shadow-lg'
                  : 'hover:bg-slate-800 hover:text-white'
                }`
              }
            >
              <item.icon className="w-5 h-5 mr-3" />
              <span className="font-medium">{item.label}</span>
            </NavLink>
          ))}
        </nav>

        <div className="p-4 border-t border-slate-800 flex flex-col gap-2">
          {(user?.role === 'Admin' || user?.role === 'DBA') && (
            <button
              onClick={confirmReport}
              className="flex items-center w-full px-4 py-2 text-sm font-medium text-emerald-400 hover:bg-slate-800 hover:text-emerald-300 rounded-md transition-colors"
            >
              <FileText className="w-4 h-4 mr-3" />
              Generate Report
            </button>
          )}
          <div className="text-center text-xs text-slate-600 mt-2">
            &copy; 2026 GrocerySys
          </div>
        </div>
      </aside>

      {/* Report Modal */}
      {isReportModalOpen && (
        <Modal isOpen={isReportModalOpen} onClose={() => setIsReportModalOpen(false)} title="Generate Report">
          <div className="space-y-4">
            <div className="flex items-center gap-3 text-emerald-600 bg-emerald-50 p-3 rounded-lg">
              <FileText className="w-8 h-8" />
              <div>
                <h4 className="font-bold">Operational Report</h4>
                <p className="text-xs text-slate-500">Includes Sales, Inventory, and performance metrics.</p>
              </div>
            </div>
            <p className="text-slate-600">Are you sure you want to generate and download the latest operational report?</p>
            <div className="flex justify-end gap-3">
              <button onClick={() => setIsReportModalOpen(false)} className="btn btn-secondary">Cancel</button>
              <button onClick={handleGenerateReport} className="btn bg-emerald-600 text-white hover:bg-emerald-700">Generate PDF</button>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
};


export default Sidebar;
